name: cnn_unstable_over_seeds

dataset: mnist_small

training:
  checkpoint_interval: 100
  min_epochs: 30000
  max_epochs: 100000
  convergence_tolerance: 1.0e-2 # ???

model:
  type: all_cnn_c_hidden
  hidden_units: [8, 8]
  weight_decay: 2.0e-2

  schedule:
    batch_size: 500
    initial_learning_rate: 0.0001
    learning_rate_decay_epochs: [5000, 10000]

seeds:
  count: 20

warm_start_indices: [0]

test_points:
  type: high_test_loss
  count: 50

train_points:
  type: high_influence
  count: 20
